### ISSUE TITLE
Linker error with gcc 10 and multiple translation units including superior_mysqlpp.hpp

### ISSUE THREAD

**Issue by daniele77** [seznam/SuperiorMySqlpp#132]
With recent compilers (e.g., gcc 10) the linking of multiple translation units including the header `superior_mysqlpp.hpp` results in an error. The linker complains about multiple definitions of `SuperiorMySqlpp::mapSecondGetter`.

This is because of this definition:

https://github.com/seznam/SuperiorMySqlpp/blob/05421a8f6d31bc3dc01b03f9d1b3eb524db818f6/include/superior_mysqlpp/master_slave_connection_pools.hpp#L20)

I provided a solution to this issue in the PR #131

**Comment by OpatrilPeter** [comment]
Closed by #134
