### ISSUE TITLE
DBDriver::Result::freeResult() is useless

### ISSUE THREAD

**Issue by smradCZ** [seznam/SuperiorMySqlpp#80]
I think the method DBDriver::Result::freeResult() should be removed. It calls `mysql_free_result` but it will be done automatically in class destructor.

In case the method is really wanted, then some things should be updated:
- it should return `void` instead of magic `auto`
- it should set `resultPtr` to `nullptr` after calling `mysql_free_result` method to ensure destructor won't freeing memory on same pointer again.

**Comment by majcl** [comment]
Merged into devel by pull request #101
