### ISSUE TITLE
How to use this client with multi master mode of MySQL with Galera cluster enabled

### ISSUE THREAD

**Issue by techwizardg** [seznam/SuperiorMySqlpp#86]
On the server side, we have MySQL with Galera cluster enabled(i.e. multi master mode). Can I use this client to access the galera cluster?(i.e. does this MySQL client support multi master mode). This is not an issue and did not know where else to post so writing it here

**Comment by smradCZ** [comment]
Hello, I'm very sorry for totally late answer.

Yes, you can use this library with Galera cluster.
But the library has currently implemented only master-slave pool which can be used for your scenario if you can live without multi-master advantages or you can write own pool for it.

Maybe we add support for multi-master pool in future releases, but I can't promise it now.
